

# train|inference
mode: train

# cpu | cuda
device: cpu

logging_level: INFO

dataloader:
  batch_size: 4
  

data:
  aneks_path:
    train: data/aneks/processed/aneks.json
    test: data/aneks/processed/aneks.json
  vocab_path: data/vocab/
